# Generated by Django 4.2 on 2025-04-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=10)),
                ('category', models.CharField(default='any', max_length=50)),
                ('difficulty', models.CharField(choices=[('any', 'Any Difficulty'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='any', max_length=10)),
                ('quiz_type', models.CharField(choices=[('any', 'Any Type'), ('multiple', 'Multiple Choice'), ('boolean', 'True / False')], default='any', max_length=10)),
                ('encoding', models.CharField(choices=[('default', 'Default Encoding'), ('urlLegacy', 'Legacy URL Encoding'), ('url3986', 'URL Encoding (RFC 3986)'), ('base64', 'Base64 Encoding')], default='default', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizconfiguration')),
            ],
        ),
    ]
